name: generate fonts

on:
  workflow_dispatch:
    inputs:
      target_job:
        description: 'Which job to run'
        required: true
        default: 'get-infomation'

concurrency: generate-fonts

jobs:
  get-infomation:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-latest-version.outputs.tag }}
      version: ${{ steps.get-latest-version.outputs.version }}
    steps:
      - name: Get the latest version of Sarasa Gothic
        id: get-latest-version
        uses: actions/github-script@v8
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
                owner: "be5invis",
                repo: "Sarasa-Gothic",
            });
            core.setOutput('tag', release.tag_name);
            const version = release.tag_name.match(/^v(\d+\.\d+\.\d+)/);
            core.setOutput('version', version[1]);

  prepare:
    runs-on: ubuntu-latest
    needs: get-infomation
    env:
      LATEST_TAG: ${{ needs.get-infomation.outputs.tag }}
      LATEST_VERSION: ${{ needs.get-infomation.outputs.version }}
    steps:
      - run: echo tag is ${{ env.LATEST_TAG }}
      - run: echo version is ${{ env.LATEST_VERSION }}

      - name: Download latest version of Sarasa Gothic from GitHub release page
        uses: robinraju/release-downloader@v1
        with:
          repository: 'be5invis/Sarasa-Gothic'
          tag: ${{ env.LATEST_TAG }}
          fileName: 'Sarasa-TTF-${{ env.LATEST_VERSION }}.7z'
      - run: ls -l

      - name: Upload sarasa-gothic-ttf.7z
        uses: actions/upload-artifact@v4
        with:
          name: sarasa-gothic-ttf.7z
          path: '*.7z'

  patch1:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        styles: ['fixed']
        orthographies: ['sc']
        variants:
          [
            'regular',
            'italic',
            'bold',
            'bolditalic',
            'semibold',
            'semibolditalic',
            'light',
            'lightitalic',
            'extralight',
            'extralightitalic',
          ]
    env:
      FILENAME: 'sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}'
      NERD_FONTS_VERSION: v3.4.0
    steps:
      - uses: actions/checkout@v4

      # credits: https://github.com/adam7/delugia-code/blob/411f2aecdef35d6bb92776d26bb5efe4ee799e0a/.github/workflows/ci.yaml#L77-L100
      - name: Fetch FontForge
        run: |
          sudo apt install software-properties-common python3-fontforge fuse -y -q
          curl -L "https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage" --output fontforge
          chmod u+x fontforge
          echo Try appimage
          ./fontforge --version
          echo `pwd` >> $GITHUB_PATH
          echo Try appimage with path
          fontforge --version
      - name: Get Font Patcher
        uses: robinraju/release-downloader@v1
        with:
          repository: 'ryanoasis/nerd-fonts'
          tag: ${{ env.NERD_FONTS_VERSION }}
          fileName: 'FontPatcher.zip'
      - name: Open Font Patcher release
        run: |
          unzip FontPatcher.zip

      - run: tree .
      - name: Download sarasa-gothic-ttf.7z
        uses: actions/download-artifact@v4
        with:
          name: sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: install configparser
        run: pip install configparser
      - run: ls -l
      - name: Rename target filename
        run: |
          matrix_style=${{ matrix.styles }}
          matrix_style=${matrix_style/-slab/Slab}
          original_style=${matrix_style^}
          echo original_style is ${original_style}

          matrix_orthography=${{ matrix.orthographies }}
          original_orthography=${matrix_orthography^^}
          echo original_orthography is ${original_orthography}

          matrix_variant=${{ matrix.variants }}
          matrix_variant=${matrix_variant/italic/Italic}
          matrix_variant=${matrix_variant/bold/Bold}
          matrix_variant=${matrix_variant/light/Light}
          original_variant=${matrix_variant^}
          echo original_variant is ${original_variant}

          original_filename="Sarasa${original_style}${original_orthography}-${original_variant}"
          echo original_filename is ${original_filename}

          mv "${original_filename}.ttf" "${FILENAME}.ttf"
      - run: ls -l
      - run: mkdir -p "${PWD}/outputs"
      - name: patch font
        run: fontforge -script "${PWD}/font-patcher" --adjust-line-height --careful --complete --no-progressbars --quiet "${PWD}/${FILENAME}.ttf" --outputdir "${PWD}/outputs"
      - run: ls -l
      - run: ls -l "${PWD}/outputs"
      - name: rename patched font files
        run: |
          cd "${PWD}/outputs"
          mv *.ttf "../${FILENAME}-nerd-font.ttf"
      - run: ls -l
      - name: install fonttools
        run: pip install fonttools
      - name: correcting xAvgCharWidth to fix alignment issue
        if: ${{ matrix.styles != 'gothic' && matrix.styles != 'ui' }}
        run: |
          ttx -t "OS/2" "${FILENAME}.ttf"
          ttx -t "OS/2" "${FILENAME}-nerd-font.ttf"
          ls -l *.ttx
          cat "${FILENAME}.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          original_x_avg_char_width="$(grep xAvgCharWidth "${FILENAME}.ttx" | cut -d '"' -f 2)"
          echo original xAvgCharWidth is $original_x_avg_char_width
          sed -i "s/xAvgCharWidth value=\"[0-9]\+\"/xAvgCharWidth value=\"${original_x_avg_char_width}\"/g" "${FILENAME}-nerd-font.ttx"
          cat "${FILENAME}-nerd-font.ttx"
          mv "${FILENAME}-nerd-font.ttf" "${FILENAME}-nerd-font.original.ttf"
          ttx -o "${FILENAME}-nerd-font.ttf" -m "${FILENAME}-nerd-font.original.ttf" "${FILENAME}-nerd-font.ttx"
      - name: build hdmx table to fix alignment issue
        if: ${{ matrix.styles != 'gothic' && matrix.styles != 'ui' }}
        run: python build-hdmx-for-sarasa.py "${FILENAME}-nerd-font.ttf"
      - name: patch TTF font family name
        run: python patch-ttf-name-for-sarasa-nerd.py "${FILENAME}-nerd-font.ttf" ${{ matrix.styles }} ${{ matrix.orthographies }} ${{ matrix.variants }} ${{ env.NERD_FONTS_VERSION }} ${{ github.ref_name }}
      - name: upload patched font
        uses: actions/upload-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }} font
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf

  zip:
    needs: patch1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        styles: ['fixed']
        orthographies: ['sc']
    steps:
      # start of part generated by `generate-download-patched-fonts` script
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-regular font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-italic font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-bold font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-bolditalic font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-semibold font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-semibolditalic font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-light font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-lightitalic font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-extralight font
      - uses: actions/download-artifact@v4
        with:
          name: patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-extralightitalic font
      # end of part generated by `generate-download-patched-fonts` script

      - run: ls -l
      - name: zip patched font files
        run: zip -r sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-*-nerd-font.ttf
      - run: ls -l
      - name: upload zip
        uses: actions/upload-artifact@v4
        with:
          name: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip

  release:
    needs: zip
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
      - uses: actions/download-artifact@v4
        with:
          name: sarasa-fixed-sc-nerd-font.zip


      - run: ls -l
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.zip'
          token: ${{ secrets.WORKFLOW_PERSONAL_ACCESS_TOKEN }}
